<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2011 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'kr_dealers_modified_user' => 
  array (
    'id' => '1e13f437-77cf-4886-b3bd-533416e1c0df',
    'relationship_name' => 'kr_dealers_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'kr_Dealers',
    'rhs_table' => 'kr_dealers',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'kr_dealers_created_by' => 
  array (
    'id' => '1e709f5c-3189-67bd-de05-53341654e95f',
    'relationship_name' => 'kr_dealers_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'kr_Dealers',
    'rhs_table' => 'kr_dealers',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'kr_dealers_assigned_user' => 
  array (
    'id' => '1ed5257b-98c7-86f2-da5a-533416fef52f',
    'relationship_name' => 'kr_dealers_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'kr_Dealers',
    'rhs_table' => 'kr_dealers',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'kr_dealers_documents_1' => 
  array (
    'id' => '9aa05bf6-8e36-fe45-72f2-5334160a00f7',
    'relationship_name' => 'kr_dealers_documents_1',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Documents',
    'rhs_table' => 'documents',
    'rhs_key' => 'id',
    'join_table' => 'kr_dealers_documents_1_c',
    'join_key_lhs' => 'kr_dealers_documents_1kr_dealers_ida',
    'join_key_rhs' => 'kr_dealers_documents_1documents_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'kr_dealers_kr_violation_1' => 
  array (
    'id' => '9d1095f5-5595-1c3c-a202-533416bcbf5e',
    'relationship_name' => 'kr_dealers_kr_violation_1',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'kr_Violation',
    'rhs_table' => 'kr_violation',
    'rhs_key' => 'id',
    'join_table' => 'kr_dealers_kr_violation_1_c',
    'join_key_lhs' => 'kr_dealers_kr_violation_1kr_dealers_ida',
    'join_key_rhs' => 'kr_dealers_kr_violation_1kr_violation_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'kr_dealers_activities_1_calls' => 
  array (
    'id' => '9f70e4a7-77ac-08ed-3151-5334168b50af',
    'relationship_name' => 'kr_dealers_activities_1_calls',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'kr_Dealers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'kr_dealers_contacts_1' => 
  array (
    'id' => 'a23076b6-db3c-8ccf-4647-533416024463',
    'relationship_name' => 'kr_dealers_contacts_1',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Contacts',
    'rhs_table' => 'contacts',
    'rhs_key' => 'id',
    'join_table' => 'kr_dealers_contacts_1_c',
    'join_key_lhs' => 'kr_dealers_contacts_1kr_dealers_ida',
    'join_key_rhs' => 'kr_dealers_contacts_1contacts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'kr_dealers_activities_1_meetings' => 
  array (
    'id' => 'a2a1a95e-c589-80f3-03e9-5334161f636b',
    'relationship_name' => 'kr_dealers_activities_1_meetings',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'kr_Dealers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'kr_dealers_kr_website_1' => 
  array (
    'id' => 'a5ded4ad-2c07-4272-fbe5-533416a79d7d',
    'relationship_name' => 'kr_dealers_kr_website_1',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'kr_website',
    'rhs_table' => 'kr_website',
    'rhs_key' => 'id',
    'join_table' => 'kr_dealers_kr_website_1_c',
    'join_key_lhs' => 'kr_dealers_kr_website_1kr_dealers_ida',
    'join_key_rhs' => 'kr_dealers_kr_website_1kr_website_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'kr_dealers_project_1' => 
  array (
    'id' => 'a7d388e8-d655-9b5f-9a7a-533416821847',
    'relationship_name' => 'kr_dealers_project_1',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Project',
    'rhs_table' => 'project',
    'rhs_key' => 'id',
    'join_table' => 'kr_dealers_project_1_c',
    'join_key_lhs' => 'kr_dealers_project_1kr_dealers_ida',
    'join_key_rhs' => 'kr_dealers_project_1project_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'kr_dealers_cases_1' => 
  array (
    'id' => 'b72c6cc3-50ab-1666-357a-533416bf060b',
    'relationship_name' => 'kr_dealers_cases_1',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Cases',
    'rhs_table' => 'cases',
    'rhs_key' => 'id',
    'join_table' => 'kr_dealers_cases_1_c',
    'join_key_lhs' => 'kr_dealers_cases_1kr_dealers_ida',
    'join_key_rhs' => 'kr_dealers_cases_1cases_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'kr_dealers_activities_1_notes' => 
  array (
    'id' => 'b792aabf-602d-85c1-82ba-533416c00deb',
    'relationship_name' => 'kr_dealers_activities_1_notes',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'kr_Dealers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'kr_dealers_activities_1_tasks' => 
  array (
    'id' => 'b8bc54b4-4270-70e6-be7e-53341671e0f4',
    'relationship_name' => 'kr_dealers_activities_1_tasks',
    'lhs_module' => 'kr_Dealers',
    'lhs_table' => 'kr_dealers',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'kr_Dealers',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'kr_dealers_kr_dealers_1' => 
  array (
    'rhs_label' => 'Linked Partners',
    'lhs_label' => 'Partners',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'kr_Dealers',
    'rhs_module' => 'kr_Dealers',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'kr_dealers_kr_dealers_1',
  ),
);